services:
   postgres:
     container_name: clot_db
     image: "postgres:16"
     environment:
       - "POSTGRES_DB=clot"
       - "POSTGRES_PASSWORD=secret"
       - "POSTGRES_USER=myuser"
     ports:
       - "5432:5432"
#  mysql:
#    image: "mysql:latest"
#    environment:
#      - "MYSQL_DATABASE=voucher"
#      - "MYSQL_PASSWORD=secret"
#      - "MYSQL_ROOT_PASSWORD=secret"
#      - "MYSQL_USER=myuser"
#    ports:
#      - "3306:3306"
