services:
   postgres:
     container_name: clot_db
     image: "postgres:16"
     environment:
       - "POSTGRES_DB=clot"
       - "POSTGRES_PASSWORD=secret"
       - "POSTGRES_USER=myuser"
     ports:
       - "5432:5432"
