name: Deploy Backend to EC2

on:
  push:
    branches:
      - main  # Cambia esto a la rama que uses para producción

env:
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ${{ secrets.EC2_USER }}
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ env.EC2_SSH_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r . ${EC2_USER}@${EC2_HOST}:/home/${EC2_USER}/backend

      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << 'EOF'
          cd /home/${EC2_USER}/backend
          docker-compose down
          docker-compose up -d
          EOF